String descFlutter =
    'Since its introduction by Google in May 2017, Flutter immediately garnered attention. This UI toolkit from Google enables developers to create applications for various mobile platforms such as Android and iOS. In its latest development, Flutter is not only used for mobile platforms but has also expanded to web and desktop applications. Flutter has been adopted by various major companies including Google, Alibaba.com, and Tencent.';
String descJavascript =
    'JavaScript is a programming language that is essential for a web developer to master. Initially, this language was used to make websites more interactive. As it has evolved, JavaScript is not only used in web browsers but can also run on servers. This means JavaScript is used in all parts of a website, from front-end to back-end. Furthermore, JavaScript has now started to expand to other platforms such as mobile, desktop, and games.';
String descKotlin =
    'Kotlin merupakan bahasa utama yang digunakan dalam pengembangan Android saat ini. Hal ini karena manfaat yang diberikan seperti ringkas, cepat, dan aman. Selain itu, sifatnya yang interoperability membuat developer bisa beralih dari bahasa Java ke Kotlin dengan cepat. Tak ayal, Google pernah melaporkan hampir 80% dari 1000 aplikasi teratas di Play Store menggunakan Kotlin. Selain pengembangan Android, Kotlin dapat digunakan untuk berbagai macam pengembangan, baik itu server, back-end, maupun website.';
String descPython =
    'Python is an interpreted programming language that can be used on various platforms, with a design philosophy that emphasizes code readability. It is a popular language closely associated with Data Science and Machine Learning. Python\'s interpretative nature is also widely used for prototyping, scripting in infrastructure management, and building large-scale websites. With the ease of Python, it is often chosen as the first language for learning programming.';
String descReact =
    'The demands in developing web applications are becoming increasingly complex day by day. This is because web applications today can perform like native applications. As the requirements become more intricate, the tools for web development are also becoming more sophisticated. The use of React as a tool for building user interfaces (UI) dominates the field, from startups to large multinational companies. In Indonesia, React has been trusted and used by major companies such as Tokopedia, Traveloka, and others.';
String descSwift =
    'Since its introduction at the Apple Worldwide Developer Conference (WWDC) in 2014, Swift has become the official language developed by Apple Inc. for the development of iOS, iPadOS, macOS, watchOS, tvOS, and Linux applications. Swift is a modern, fast, and type-safe programming language. Furthermore, Swift is an evolution of the Objective-C language, making it easier to learn and read. There is no doubt that the community of Swift enthusiasts will continue to grow in the near future, and you might be one of them.';
